spring.application.name=product-service
server.port=8080

# MongoDB connection (kh�ng d�ng user/pass)
spring.data.mongodb.uri=mongodb://localhost:27017/productdb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=productdb

